--- 
- 
- name: santosh
  hosts: all
  local_action: ec2
  become: no
  instance_type: {{t2.small}}
  image: {{ami-01945499792201081}}
  region: {{us-east-1}}
  keypair: {{awx}}
  count: {{1}}
  instance_profile_name: {{Vihaan}}
  group: {{	sg-08ba838d51dcadfc9}}
  wait: true
  volumes: {{30}}
  register: ec2
