- hosts: all
  gather_facts: false
  
  tasks:
    - name: Provision {{ 1 }} instances with tag {{ Santosh }}
      local_action:
        module: ec2
        key_name: "{{ awxtest }}"
        group_id: "{{ sg-06b9faa636832f768 }}"
        instance_type: "{{ t2.small }}"
        image: "{{ i-0fd39ab83cf84da48 }}"
        vpc_subnet_id: "{{ subnet-0b5fe7c228a362a12 }}"
        region: "{{ us-east-1 }}"
        assign_public_ip: yes
        wait: true
        exact_count: "{{ 1 }}"
        count_tag:
          Role: "{{ test }}"
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: "{{ 10 }}"
            delete_on_termination: true
      register: ec2
