- hosts: localhost
  connection: local
  gather_facts: false
  user: root
  
  tasks:
    - name: Provision {{ 1 }} instances with tag {{ Santosh }}
      local_action:
        module: ec2
        key_name: "{{ awx }}"
        group_id: "{{ sg-08ba838d51dcadfc9 }}"
        instance_type: "{{ t2.small }}"
        image: "{{ ami-01945499792201081 }}"
        vpc_subnet_id: "{{ subnet-08f4e1863e7c6d33c }}"
        region: "{{ us-east-1 }}"
        assign_public_ip: yes
        wait: true
        exact_count: "{{ 1 }}"
        count_tag:
          Role: "{{ test }}"
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: "{{ 10 }}"
            delete_on_termination: true
      register: ec2
