- hosts: all
  gather_facts: false
    
- name: create VPC
  ec2_vpc_net:
    name: "{{ Santosh }}"
    cidr_block: "{{ 10.145.0.0/16 }}"
    region: "{{ us-east-1 }}"
    state: present
  register: vpc
